In [1]:
import numpy as np

In [2]:
a=np.random.randint(10,50,(6,5))
a

array([[10, 39, 35, 40, 13],
       [33, 45, 11, 35, 24],
       [41, 30, 39, 44, 26],
       [49, 37, 26, 20, 44],
       [46, 37, 22, 22, 23],
       [19, 46, 40, 13, 46]])

In [3]:
a[3:5,:2]

array([[49, 37],
       [46, 37]])

In [15]:
a[2:4,2:5]

array([[39, 44, 26],
       [26, 20, 44]])